// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yafjkpckhzpkrptmzcms.supabase.co"
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZmprcGNraHpwa3JwdG16Y21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxNTk0MjEsImV4cCI6MjA4MDczNTQyMX0.T9lRcZSk-6UtywyLHYbSwzzXwns31Aj4sLyqWzICPBM"


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});